# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "SE-9" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Create properties file
      run: |
        cd src/main/resources
        touch application.properties
        echo apiVersion="v1" >> application.properties
        echo apiPrefix="api" >> application.properties
        echo selflearn.app.jwtSecret=$${{secrets.JWT_SECRET}} >> application.properties
        echo selflearn.app.jwtExpirationMs = "86400000" >> application.properties
        echo selflearn.app.jwtRefreshExpirationMs = "2628000000000" >> application.properties
        echo spring.jpa.properties.hibernate.dialect = "org.hibernate.dialect.PostgreSQLDialect" >> application.properties
        spring.jpa.hibernate.ddl-auto = "update" >> application.properties
        spring.datasource.url = ${{secrets.DATASOURCE_URL}} >> application.properties
        selflearn.git.owner = "phhytrg" >> application.properties
        selflearn.git.repo = "selflearn" >> application.properties
        selflearn.git.api.host = "api.github.com" >> application.properties
        selflearn.git.token = ${{secrets.GIT_TOKEN}} >> application.properties
        selflearn.git.baseDir = "sample" >> application.properties
        selflearn.git.observeBranch = "observe" >> application.properties
        cat src/main/resources/application.properties
    # - name: Write Properties
    #   uses: christian-draeger/write-properties@1.1.0
    #   with: 
    #     path: 'src/main/resources/application.properties'
    #     property: |
    #       'apiVersion'
    #       'apiPrefix'
    #       'selflearn.app.jwtSecret'
    #       'selflearn.app.jwtExpirationMs'
    #       'selflearn.app.jwtRefreshExpirationMs'
    #       'spring.jpa.properties.hibernate.dialect'
    #       'spring.jpa.hibernate.ddl-auto'
    #       'spring.datasource.url'
    #       'spring.jpa.show-sql'
    #       'selflearn.git.owner'
    #       'selflearn.git.repo'
    #       'selflearn.git.api.host'
    #       'selflearn.git.token'
    #       'selflearn.git.baseDir'
    #       'selflearn.git.observeBranch'
    #     value: |
    #       'v1'
    #       'api'
    #       ${{secrets.JWT_SECRET}}
    #       '86400000'
    #       '2628000000000'
    #       'org.hibernate.dialect.PostgreSQLDialect'
    #       'update'
    #       ${{secrets.DATASOURCE_URL}}
    #       'true'
    #       'phhytrg'
    #       'selflearn'
    #       'api.github.com'
    #       ${{secrets.GIT_TOKEN}}
    #       'sample'
    #       'observe'
          
    - name: Build with Maven
      run: mvn clean install
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and Push docker
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: phhytrg/selflearn
        tags: v1, latest
        registry: docker.io
        dockerfile: ./backend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'selflearn-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_62170a77871144c58e9c6230b85f04b1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_62a4f0fb89ac4f17b1f2dea304dd92f0 }}/sefllearn:${{ github.sha }}'

        
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
