# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - selflearn-api

on:
  push:
    branches:
      - SE-9
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f069305bae084acf825e5a69715508be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6467e0af35bf4172af5f8e45e17e346b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f069305bae084acf825e5a69715508be }}/phhytrg/selflearn:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'selflearn-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fcd212db1aa24262b268982d2654c9a3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f069305bae084acf825e5a69715508be }}/phhytrg/selflearn:${{ github.sha }}'